<?php
declare(strict_types=1);

require_once __DIR__ . '/_init.php';

require_once INCLUDES_DIR . '/config.php';
require_once INCLUDES_DIR . '/db.php';

$token = $_GET['token'] ?? '';
if ($token === '' || !preg_match('/^[a-f0-9]{32}$/i', $token)) {
    http_response_code(400);
    echo 'Invalid share link';
    exit;
}

$pdo = db();
$stmt = $pdo->prepare(
    'SELECT r.id, r.title, r.summary, r.markdown, r.model, r.created_at, f.name AS friend_name, s.session_id, r.is_multi_friend, r.is_multi_session
     FROM reports r
     LEFT JOIN friends f ON f.id = r.friend_id
     LEFT JOIN sessions s ON s.id = r.session_id
     WHERE r.share_token = :tok'
);
$stmt->execute([':tok' => strtolower($token)]);
$report = $stmt->fetch();
if (!$report) {
    http_response_code(404);
    echo 'Report not found or link expired';
    exit;
}

$title = html_safe($report['title']);
$friend = html_safe($report['friend_name'] ?? 'unknown');
$session = html_safe($report['session_id'] ?? 'unknown');
$scope = $report['is_multi_friend'] ? 'multi-friend' : ($report['is_multi_session'] ? 'multi-session' : "$friend / $session");
$mdToHtml = function (string $md): string {
    $md = html_safe($md);
    $md = preg_replace('/^######\s+(.+)$/m', '<h6>$1</h6>', $md);
    $md = preg_replace('/^#####\s+(.+)$/m', '<h5>$1</h5>', $md);
    $md = preg_replace('/^####\s+(.+)$/m', '<h4>$1</h4>', $md);
    $md = preg_replace('/^###\s+(.+)$/m', '<h3>$1</h3>', $md);
    $md = preg_replace('/^##\s+(.+)$/m', '<h2>$1</h2>', $md);
    $md = preg_replace('/^#\s+(.+)$/m', '<h1>$1</h1>', $md);
    $md = preg_replace('/\*\*(.+?)\*\*/', '<strong>$1</strong>', $md);
    $md = preg_replace('/\*(.+?)\*/', '<em>$1</em>', $md);
    $md = preg_replace('/^\s*-\s+(.+)$/m', '<li>$1</li>', $md);
    $md = preg_replace('/^\s*\d+\.\s+(.+)$/m', '<li>$1</li>', $md);
    $md = preg_replace('/(&lt;li&gt;.+?&lt;\/li&gt;\n?)+/s', '<ul>$0</ul>', $md);
    $md = nl2br($md);
    return $md;
};
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $title; ?> — ArmaLogs Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background:#0f172a; color:#e2e8f0; margin:0; padding:24px; line-height:1.6; }
    .container { max-width:900px; margin:0 auto; background:#1e293b; border-radius:12px; padding:32px; box-shadow:0 10px 30px rgba(0,0,0,.4); }
    h1 { margin-top:0; font-size:1.75rem; }
    h2 { border-bottom:1px solid #334155; padding-bottom:8px; margin-top:32px; }
    .meta { color:#94a3b8; font-size:.875rem; margin-bottom:24px; }
    a { color:#60a5fa; }
    ul { padding-left:20px; }
    li { margin:6px 0; }
    strong { color:#f8fafc; }
  </style>
</head>
<body>
  <div class="container">
    <div class="meta">
      Shared ArmaLogs report · <?php echo $scope; ?> · <?php echo $report['created_at']; ?>
      <?php if ($report['model']) { echo ' · Model: ' . html_safe($report['model']); } ?>
    </div>
    <h1><?php echo $title; ?></h1>
    <div class="report">
      <?php echo $mdToHtml($report['markdown'] ?: $report['summary']); ?>
    </div>
    <p style="margin-top:40px; font-size:.8rem; color:#64748b;">Generated by ArmaLogs</p>
  </div>
</body>
</html>
